* 上古神器-awk
** awk 语法
   最简单的awk 程序是一个由多个模式–动作语句构成的序列:
   #+BEGIN_SRC 
      pattern { action }
      pattern { action }
   #+END_SRC
*** 模式
   模式汇总
   1. BEGIN{ statements}
      在输入被读取之前, statements 执行一次.
   2. END{ statements}
      当所有输入被读取完毕之后, statements 执行一次.
   3. expression{ statements}
      每碰到一个使expression 为真的输入行, statements 就执行. expression 为真指的是其值非零或非空.
   4. regular expression { statements}
      当碰到这样一个输入行时, statements 就执行: 输入行含有一段字符串, 而该字符串可以被regular expression 匹配.
   5. compound pattern { statements}
      一个复合模式将表达式用&&(AND), ||(OR), !(NOT), 以及括号组合起来; 当compound pattern为真时, statements 执行.
   6. pattern1, pattern2 { statements}
      一个范围模式匹配多个输入行, 这些输入行从匹配pattern1 的行开始, 到匹配pattern2 的行结束(包括这两行), 对这其中的每一行执行statements

   BEGIN 与END 不与其他模式组合. 一个范围模式不能是其他模式的一部分. BEGIN 与END 是唯一两个不能省略动作的模式.
** awk 常用命令
   1. kill 进程
      ps aux|grep test.py|awk '{print $2}'|xargs kill -9
   2. 两文件比较 取相同部分
      awk -F ':' 'NR==FNR{a[$1]++}NR!=FNR{if($1 in a){print $i}}' 1 2 >3

      输出2在1中第一列相同的所有值
   3. 输出3文件内 大于10列
      awk 'NF>10 {print $i}' 3 > 4
